In [1]:
# import lib
import numpy as np
from numpy.random import rand

In [2]:
# dataset
x = np.array(([0.9,0.8],[0.6,0.3],[0.9,0.1],[0.9,0.8]))
y = np.array(([0],[1],[1],[0]))


In [8]:
# activation function
def sigmoid(z):
    return 1/(1+np.exp(-z))

# Mulity-layers feedforward neural network (2 hidden layers)
class NeuralNetwork:
    # constructor
    def __init__(self , x , y , nodes_in_layer1 = 4 , nodes_in_layer2 = 3 , nodes_in_layer3 = 1):
        # definde x ,y
        self.inputs_in_layer0 = x
        self.y = y

        # definde and set the number of nurons in each layers
        self.nodes_in_layer1 = nodes_in_layer1
        self.nodes_in_layer2 = nodes_in_layer2
        self.nodes_in_layer3 = nodes_in_layer3

        # weights (theta) metrix
        self.thetas_layer0 = np.random.rand(self.inputs_in_layer0.shape[1] + 1,self.nodes_in_layer1)
        self.thetas_layer1 = np.random.rand(self.nodes_in_layer1 + 1,self.nodes_in_layer2)
        self.thetas_layer2 = np.random.rand(self.nodes_in_layer2 + 1,nodes_in_layer3)
    # feedforward 
    def feedforward(self):
       
       self.Z1 = self.thetas_layer0[0] + np.dot(self.inputs_in_layer0,self.thetas_layer0[1:])
       self.later1 = sigmoid(self.Z1)

       self.Z2 = self.thetas_layer1[0] + np.dot(self.later1,self.thetas_layer1[1:])
       self.later2 = sigmoid(self.Z2)

       self.Z3 = self.thetas_layer2[0] + np.dot(self.later2,self.thetas_layer2[1:])
       self.later3 = sigmoid(self.Z3)

       return self.later3

In [12]:
NN = NeuralNetwork(x,y)
predicted_output = NN.feedforward()
print("accuracy output: \n",y)
print("predicted output \n",predicted_output)

accuracy output: 
 [[0]
 [1]
 [1]
 [0]]
predicted output 
 [[0.88873483]
 [0.88698848]
 [0.88703891]
 [0.88873483]]


In [22]:
NN.later3
# Last video of the series = L4

array([[0.88873483],
       [0.88698848],
       [0.88703891],
       [0.88873483]])